packages:
  - packages/*
  - playground
  - docs

defines:
  - &babel ^7.28.0
  - &vue-macros ^3.0.0-beta.19
  - &ts-macro ^0.2.7
  - &vue 3.6.0-alpha.2

catalog:
  '@babel/core': *babel
  '@babel/parser': *babel
  '@babel/plugin-syntax-jsx': ^7.27.1
  '@babel/plugin-transform-typescript': ^7.28.0
  '@babel/traverse': *babel
  '@babel/types': *babel
  '@types/babel__core': ^7.20.5

  '@nuxt/kit': ^3.17.6
  '@nuxt/schema': ^3.17.6

  '@vue/compiler-dom': *vue
  '@vue/compiler-sfc': *vue
  '@vue/shared': *vue

  '@vue-macros/common': *vue-macros
  '@vue-macros/define-render': *vue-macros
  '@vue-macros/jsx-directive': *vue-macros
  '@vue-macros/test-utils': *vue-macros
  '@vue-macros/volar': *vue-macros

  '@ts-macro/tsc': *ts-macro
  '@types/hash-sum': ^1.0.2
  ast-kit: ^2.1.1
  hash-sum: ^2.0.0
  source-map-js: ^1.2.1
  ts-macro: *ts-macro
  unplugin: ^2.3.5
  unplugin-utils: ^0.2.4
  vite: ^7.0.5
  vitest: ^3.2.4
  vue: *vue
